version: '3.8'

services:
  prod-db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "secret"
      POSTGRES_USER: "prod_user"
      POSTGRES_DB: "nestjs_db_prod"
    ports:
    - 5433:5432
  dev-db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "secret"
      POSTGRES_USER: "prod_user"
      POSTGRES_DB: "nestjs_db_test"
    ports:
    - 5434:5432

networks:
  nestjs_crud_api: